const REFUND_DEADLINE_HOURS = {
  BEFORE_6H: 6,
  BEFORE_12H: 12,
  BEFORE_6H_END: 6
};

const WALLET_CONSTANTS = {
  MIN_WITHDRAWAL_AMOUNT: 1,
  MAX_WITHDRAWAL_AMOUNT: 10000,
  DAILY_WITHDRAWAL_LIMIT: 3,
  MONTHLY_WITHDRAWAL_LIMIT: 30000,
  WITHDRAWAL_FEE_RATE: 0.001
};

const TICKET_CONSTANTS = {
  TICKET_CODE_RANDOM_MAX: 10000
};

const SETTLEMENT_CONSTANTS = {
  SETTLEMENT_DELAY_DAYS: 5
};

const VIP_CONSTANTS = {
  MILLISECONDS_PER_DAY: 24 * 60 * 60 * 1000
};

const CACHE_CONSTANTS = {
  DEFAULT_CACHE_TTL: 3600,
  RECONNECT_DELAY_MAX: 50
};

const ORDER_PREFIX = {
  ORDER: 'ORD',
  PAYMENT: 'PAY',
  REFUND: 'REF',
  TICKET: 'TKT'
};

module.exports = {
  REFUND_DEADLINE_HOURS,
  WALLET_CONSTANTS,
  TICKET_CONSTANTS,
  SETTLEMENT_CONSTANTS,
  VIP_CONSTANTS,
  CACHE_CONSTANTS,
  ORDER_PREFIX
};
